# config.toml

# Uncomment and modify these lines to override default values
# ipc_path = "/tmp/reth.ipc"
# future_block_offset = 10
# state_file = "budget_system_state.json"
# script_file = "input_script.json"
# default_total_counted_seats = 7
# default_max_earner_seats = 5
# default_qualified_majority_threshold = 0.7
# counted_vote_points = 5
# uncounted_vote_points = 2